import colorama, os, time
from colorama import Fore, Style

print(f"{Style.DIM}Loader.py by Loannn{Style.NORMAL}")
time.sleep(2)

print("\nInstalling packages...")
time.sleep(1.0069)
print("Importing packages...")
time.sleep(0.420)
print(f"{Fore.GREEN}Succesfully imported packages!")
time.sleep(0.7)
print("\nLoading...")
time.sleep(1)
print(f"{Fore.RED}Loading failed. (Error: 69420)")
time.sleep(0.0069)
print("\nERROR")
time.sleep(0.0069)
print("ERROR")
time.sleep(0.0069)
print("ERROR")
time.sleep(0.0069)
print("ERROR")
time.sleep(0.0069)
print("ERROR")
time.sleep(0.0069)
print("ERROR")
time.sleep(0.0069)
print("ERROR")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
os.system("start cmd")
